# Generated by Django 6.0 on 2025-12-21 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='artistas',
            new_name='artists',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='genero_favorito',
            new_name='favourite_genre',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='canciones',
            new_name='songs',
        ),
    ]
