# Generated by Django 6.0 on 2025-12-22 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_artistas_user_artists_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='artists',
        ),
        migrations.RemoveField(
            model_name='user',
            name='songs',
        ),
    ]
