# Generated by Django 6.0 on 2025-12-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_artists_remove_user_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='artists',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='songs',
            field=models.JSONField(default=list),
        ),
    ]
